config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations", as: :anvandare
  }

  resource :user, path: :anvandare

  # Scope to change urls to swedish
  scope path_names: { new: "ny", edit: "redigera" } do
    resources :addresses, path: :adresser

    resources :companies, path: :foretag

    resources :customers, path: :kunder do
      get :company, path: :foretag, on: :member
      resources :addresses, path: :adresser, on: :member

      resources :machines, path: :maskiner, on: :member do
        resources :works, path: :arbete, on: :member
      end
      resources :works, path: :maskiner, on: :member

    end
    resources :cities, path: :stader do
      post :search, :sok, on: :collection
    end

    resources :machines, path: :maskiner
    resources :machine_types, path: :typer
    resources :brands, path: :marke
    resources :products, path: :produkter do
      post :search, on: :collection, path: :sok
    end

    resources :roles
    resources :work_types, path: :arbetstyper
  end

  root "statics#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    elsif user.id.present?
      can [:read, :new, :create, :update, :destroy], :all
      can :search, Product
    else
      can [:new, :create], :session
    end

    if user.role.present?
      user.role.permissions.each do |permission|
        if permission.subject_class == "all"
          can permission.action.to_sym, :all
        else
          can permission.action.to_sym, permission.subject_class.constantize
        end
      end
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
  belongs_to :city

  validates :street, presence: true

  def to_s
    %(#{street}, #{city})
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :machine_models
  has_many :machine_types, through: :machine_models
  has_many :products, through: :machine_models
  has_many :parts, through: :machine_models

  validates :title, :short, presence: true
  validates :short, uniqueness: true

  def to_s
    title
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :addresses

  validates :postal_title, :postal_code, presence: true
  validates :postal_code, uniqueness: true

  def to_s
    %(#{postal_code} #{postal_title})
  end
end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :customers

  has_many :machines, through: :customers
  has_many :products, through: :machines
  has_many :addresses
  has_many :works, through: :machines
  has_many :storages, through: :works

  validates :title, presence: true

  def self.new_path(*)
    Rails.application.routes.url_helpers.new_company_path
  end

  def self.index_path
    Rails.application.routes.url_helpers.companies_path
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_paper_trail

  belongs_to :company

  has_many :machines
  has_many :products, through: :machines
  has_many :addresses
  has_many :works, through: :machines
  has_many :storages, through: :works

  validates :firstname, presence: true
  accepts_nested_attributes_for :addresses, allow_destroy: true

  def to_s
    %(#{firstname} #{lastname})
  end
end

app/models/drive.rb
class Drive < ActiveRecord::Base
  belongs_to :work
  belongs_to :address
  belongs_to :user
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_paper_trail

  belongs_to :customer
  belongs_to :product

  has_many :works
  has_many :parts_used, class_name: :Part, foreign_key: :part_id, through: :works
  has_many :parts, through: :product

  validates :customer, :product, presence: true

  def to_s
    %(#{product})
  end
end

app/models/machine_type.rb
class MachineType < ActiveRecord::Base

  has_many :products
  has_many :brands, through: :products

  validates :title, presence: true

  def to_s
    title
  end
end

app/models/part.rb
class Part < ActiveRecord::Base

  has_many :work_parts
  has_many :work_activities, through: :work_parts
  # Messy, create join models?
  has_many :works, through: :work_activities
  has_many :machines, through: :works
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :permission_roles, dependent: :destroy
  has_many :roles, through: :permission_roles

  validates :subject_class, :action, presence: true
  validates :subject_class, uniqueness: { scope: :action }


  def to_s
    %(#{action}#{subject_class})
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :parts
  belongs_to :machine_type
  belongs_to :brand

  validates :brand_id, :machine_type_id, :product_nbr,
                       presence: true

  attr_accessor :search

  def to_s
    %(#{brand} #{machine_type} #{product_nbr})
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :permissions, through: :permission_roles
  has_many :permission_roles, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/storage.rb
class Storage < ActiveRecord::Base
  belongs_to :storage_spot
  belongs_to :machine
end

app/models/storage_room.rb
class StorageRoom < ActiveRecord::Base
  has_many :storage_shelves
  has_many :storage_spots
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  devise :database_authenticatable, :rememberable, :registerable
  attr_accessor :login
  belongs_to :role
  has_many :work_activities
  has_many :works
  has_many :addresses

  #validates :username,
  #          presence: true,
  #          uniqueness: {
  #              case_sensitive: false
  #          }

  def name
    if firstname? && lastname?
      %(#{firstname} #{lastname})
    else
      email
    end
  end

  def admin?
    role.try(:title) == :admin
  end

  #def self.find_for_database_authentication(warden_conditions)
  #  conditions = warden_conditions.dup
  #  if login = conditions.delete(:login)
  #    where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
   # else
   #   where(conditions.to_hash).first
   # end
  #end

end

app/models/work.rb
class Work < ActiveRecord::Base
  has_paper_trail

  belongs_to :machine
  has_many :work_activities
  has_many :work_parts, through: :work_activities
  has_many :users, through: :work_activities
  has_many :drives
  has_one :storage

  validates :machine, presence: true
end

app/models/work_part.rb
class WorkPart < ActiveRecord::Base
  belongs_to :part
  belongs_to :work_activity
end

app/models/work_type.rb
class WorkType < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
end

app/views/elements/_attributes.html.erb
<dl class='list-unstyled'>
  <% attributes.each do |a| %>
    <dd class="">
    <% if a == :phone || a == :cellphone %>
      <%= fa_icon('phone') %>
    <% elsif a == :email %>
      <%= fa_icon('envelope') %>
    <% end %>
    <% if a == :phone || a == :cellphone %>
      <%= link_to(object.try(a),%(tel:#{object.try(a)})) %>
    <% elsif a == :email %>
      <%= link_to(object.try(a),%(mailto:#{object.try(a)})) %>
    <% elsif a == :url %>
      <%= link_to(object.try(a),object.try(a)) %>
    <% elsif a == :addresses %>
      <% if object.try(a).present? %>
        <% object.try(a).each do |add| %>
          <%= link_to(add, %(http://maps.google.com/?q=#{add}), target:'_blank')%>
        <% end %>
      <% end %>
    <% else %>
      <%= object.try(a) %>
    <% end %>
    </dd>
  <% end %>
</dl>

app/views/elements/_breadcrumbs.html.erb
<div class='breadcrumbs'>
  <div class='container'>
    <h1 class='pull-left'>Invoice</h1>
    <ul class='pull-right breadcrumb'>
      <li><a href='index.html'>Home</a></li>
      <li><a href=''>Pages</a></li>
      <li class='active'>Invoice</li>
    </ul>
  </div>
</div>

app/views/elements/_copyright.html.erb
<div class='copyright'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-12'>
        <p>
        2015 &copy; <%=link_to('David Wessman','http://github.com/davidwessman', style: 'color: #2a9a2b')%>
      </p>
      </div>
    </div>
  </div>
</div>

app/views/elements/_header.html.erb
<div class="header header-start">
  <div class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path do %>
          <div class="navbar-brand">
            <%= image_tag("logo.png", class: "logo-header") %>
          </div>
        <% end %>
      </div>
      <%= render "elements/menu" %>
    </div>
  </div>
</div>

app/views/elements/_links.html.erb
<% if !object.new_record? %>
  <%= link_to(t(%(#{object.class.name.downcase}.redigera)),
                      url_for(action: :edit, controller: '/' + object.class.name.tableize,
              id: object.id),
             class: 'btn btn-u btn-u-primary') %>
<% end %>
<br><hr>
<%= link_to(t(%(#{object.class.name.downcase}.new)),
            url_for(action: :new, controller: '/' + object.class.name.tableize),
           class: 'btn btn-u btn-u-primary') %>
<%= link_to(t('index', attribute: object.class.model_name.human(count: 2).downcase),
            url_for(action: :index, controller: '/' + object.class.name.tableize),
           class: 'btn btn-u  btn-u-primary') %>

app/views/elements/_menu.html.erb
<div class='collapse navbar-collapse navbar-responsive-collapse'>
  <ul class='nav navbar-nav navbar-right'>
    <%= render 'elements/menu_element', model: Customer %>
    <%= render 'elements/menu_element', model: Machine %>
    <%= render 'elements/menu_element', model: Company %>

    <li class='dropdown'>
      <%= link_to t('constants'), '', class: 'dropdown-toggle',
                                      data: { toggle: 'dropdown' } %>
      <ul class='dropdown-menu'>
        <%= render 'elements/submenu', model: City %>
        <%= render 'elements/submenu', model: WorkType %>
        <%= render 'elements/submenu', model: Product %>
        <%= render 'elements/submenu', model: Brand %>
        <%= render 'elements/submenu', model: MachineType %>
      </ul>
    </li>
    <% if current_user.present? %>
      <li class='dropdown'>
        <%= link_to fa_icon('user') + ' ' + current_user.firstname ,
          '', class: 'dropdown-toggle', data: { toggle: 'dropdown' } %>
        <ul class='dropdown-menu'>
          <li><%= link_to t('user.settings'), edit_user_registration_path %></li>
          <li><%= link_to t('sign_out'), :destroy_user_session, method: :delete %></li>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/elements/_menu_element.html.erb
<li class='dropdown'>
  <%= link_to(model_name(model),'', class: 'dropdown-toggle', data: {toggle: 'dropdown'}) %>
  <ul class='dropdown-menu'>
    <li><%= link_to(t(%(#{model.name.downcase}.new)),
                    url_for(action: :new, controller: '/'+model.name.tableize)) %></li>
    <li><%= link_to(t('index', attribute: model.model_name.human(count: 2).downcase),
                    url_for(action: :index, controller: '/'+model.name.tableize)) %></li>
  </ul>
</li>

app/views/elements/_navbar.html.erb
<ul class="loginbar pull-right">
  <% if user_signed_in? %>
      <li class="dropdown">
        <%= link_to(model_name(Machine), "", class: "dropdow-toggle", data: {toggle: "dropdown"}) %>
        <ul class="dropdown-menu">
          <li><%= link_to("Ny kund", new_customer_path) %></li>
          <li><%= link_to("Alla kunder", customers_path) %></li>
        </ul>
      </li>
      <li class="dropdown">
        <%= link_to fa_icon("user") + " " + current_user.email, root_path, class: "dropdown-toggle", data: {toggle: "dropdown"} %>
        <ul class="dropdown-menu">
          <li><%= link_to "Profil", "current_user" %></li>
          <li><%= link_to "Kontoinställningar", edit_user_registration_path %></li>
          <li><%= link_to "Logga ut", :destroy_user_session, method: :delete %></li>
        </ul>
      </li>
  <% else %>
      <li>
        <%= link_to fa_icon("sign-in") + ' Logga in', new_user_session_path %>
      </li>
  <% end %>
</ul>

app/views/elements/_submenu.html.erb
<li class="dropdown-submenu">
  <%= link_to(model_name(model), url_for(action: :index, controller: '/'+model.name.tableize)) %>
  <ul class="dropdown-menu pull-left">
    <li><%= link_to(t(%(#{model.name.downcase}.new)),
                    url_for(action: :new, controller: '/'+model.name.tableize)) %></li>
  </ul>
</li>

app/views/shared/_form_errors.html.erb
<% if current.errors.any? %>
    <div id="error_explanation">
      <h3><%= %(#{pluralize(current.errors.count, t(:error))} #{t(:prevent_save)}:)%> </h3>
      <ul class="list">
        <% current.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>