config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations", as: :anvandare
  }

  resource :user, path: :anvandare

  # Scope to change urls to swedish
  scope path_names: { new: "ny", edit: "redigera" } do
    resources :addresses, path: :adresser

    resources :companies, path: :foretag

    resources :customers, path: :kunder do
      get :company, path: :foretag, on: :member
      resources :addresses, path: :adresser, on: :member

      resources :machines, path: :maskiner, on: :member do
        resources :works, path: :arbete, on: :member
      end
      resources :works, path: :maskiner, on: :member

    end
    resources :cities, path: :stader do
      post :search, :sok, on: :collection
    end

    resources :machines, path: :maskiner
    resources :machine_types, path: :typer
    resources :brands, path: :marke
    resources :products, path: :produkter do
      post :search, on: :collection, path: :sok
    end

    resources :roles
    resources :work_types, path: :arbetstyper
  end

  root "statics#index"
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_paper_trail

  belongs_to :customer
  belongs_to :product

  has_many :works
  has_many :parts_used, class_name: :Part, foreign_key: :part_id, through: :works
  has_many :parts, through: :product

  validates :customer, :product, presence: true

  def to_s
    %(#{product})
  end
end

app/models/machine_type.rb
class MachineType < ActiveRecord::Base

  has_many :products
  has_many :brands, through: :products

  validates :title, presence: true

  def to_s
    title
  end
end

app/controllers/machines_controller.rb
# encoding:UTF-8
class MachinesController < ApplicationController
  load_and_authorize_resource
  load_and_authorize_resource :customer, parent: true


  def index
  end

  def show
  end

  def new
    @machine.product = Product.new
  end

  def edit
  end

  def create
    if @machine.save
      redirect_to machine_path(@machine), notice: alert_create(Machine)
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to customer_path(@customer), notice: alert_update(Machine)
    else
      render action: :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to :customers, notice: alert_destroy(Machine)
  end

  private

  def machine_params
    params.require(:machine).permit(:customer_id, :old_id,
                                    :serial_nbr, :product_id,
                                    :manufactured, :engine_nbr,
                                    :deck_nbr)
  end

  def customer_params
    params.require(:customer).permit(:firstname, :lastname, :cellphone,
                                     :phone, :email, :old_id, :comment)
  end
end

app/views/machines/_form.html.erb
<%= simple_form_for(@machine) do |f| %>
    <div class="form-inputs">
      <%= f.association :product, collection: Product.all %>
      <%= f.hidden_field :customer_id, value: @customer.try(:id) %>
      <%= f.input :serial_nbr %>
      <%= f.input :manufactured, as: :date_picker %>
      <%= f.input :engine_nbr %>
      <%= f.input :deck_nbr %>
      <%= f.input :old_id %>
    </div>

    <div class="form-group">
      <div class="col-md-offset-4 col-md-8">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    </div>

  <div class="form-inputs">
    <div class='tab-v1'>
      <ul class='nav nav-justified nav-tabs'>
        <li class='active'><a data-toggle='tab' href='#type-select'>Select WorkType</a></li>
        <li><a data-toggle='tab' href='#type-new'>New WorkType</a></li>
      </ul>
      <div class='tab-content'>
        <div id='type-select' class='brand-select tab-pane fade in active'>
          <%= f.association :product, collection: MachineType.all %>
        </div>
        <div id='type-new' class='profile-edit tab-pane fade'>
          <%= f.simple_fields_for :machine_type, MachineType.new do |p| %>
            <%= render 'machine_types/fields', var: p %>
          <% end %>
        </div>
      </div>
    </div>
    <div class='tab-v1'>
      <ul class='nav nav-justified nav-tabs'>
        <li class='active'>
          <%= link_to(t(:select, attribute: Brand.model_name.human), '#brand-select', data: { toggle: 'tab' }) %>
        </li>
        <li>
          <%= link_to(t(:new, attribute: Brand.model_name.human), '#brand-new', data: { toggle: 'tab' }) %>
        </li>
      </ul>
      <div class='tab-content'>
        <div id='brand-select' class='brand-select tab-pane fade in active'>
        </div>
        <div id='brand-new' class='brand-edit tab-pane fade'>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/machines/_machine.html.erb
<div class="team-2">
  <div class="inner-team">
    <%= customer.company.present? ? company : nil  %>
    <h3><%=%(#{customer.name} #{customer.lastname})%></h3>
    <small class="green">Maskiner: <%=customer.machines.count%></small>
    <small class="green">Uppdrag: <%=customer.works.count%></small>
  </div>
</div>

app/views/machines/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-offset-4 col-sm-6 col-sm-offset-3 reg-page">
      <%= label_tag("Redigera kund",nil, class: 'reg-header')%>
      <%= render 'form'%>
      <hr>
      <%= link_to(fa_icon('trash-o') + " Förinta", @customer, method: :delete, data: {confirm: "Är du säker?"}, class: "btn-u btn-u-small")%>
      <%= link_to(fa_icon('users') + ' Visa alla kunder', customers_path,class:"btn-u btn-u-small")%>
      <%= link_to(fa_icon('arrow-left') + ' Tillbaka till start', root_url,class:"btn-u btn-u-small")%>
    </div>
  </div>
</div>

app/views/machines/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
        <tr>
          <th>#</th>
          <th>Kund</th>
          <th>Produkt</th>
          <th>Tillverkad</th>
          <th>Serienummer</th>
          <th>Motornummer</th>
          <th>Klippdäck</th>
          <th>Gammalt ID</th>
          <th>Redigera</th>
        </tr>
        </thead>
        <tbody>
        <% @machines.each do |machine| %>
            <tr>
              <td><%= link_to(t('show'), machine) %></td>
              <td><%= machine.customer.present? ? link_to(machine.customer, machine.customer) : 'Ingen' %></td>
              <td><%= machine.product.present? ? link_to(machine.product, machine.product) : 'Ingen' %></td>
              <td><%= machine.manufactured %></td>
              <td><%= machine.serial_nbr %></td>
              <td><%= machine.engine_nbr %></td>
              <td><%= machine.deck_nbr %></td>
              <td><%= machine.old_id %></td>
              <% if machine.customer.present? %>
                  <td><%= link_to('Redigera', edit_customer_machine_path(machine.customer,machine)) %></td>
              <% else %>
                  <td><%= link_to('Redigera', edit_machine_path(machine)) %></td>
              <% end %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/machines/new.html.erb
<div class="col-xs-6">
  <%= render 'form' %>
</div>
<div class="col-xs-6">
  <%= render 'products/search', product: @machine.product %>
</div>
<%= link_to(t(:back_to_root), root_url) %>

app/views/machines/show.html.erb
<%= render @machine.customer, hover: true %>
<%= render 'elements/links', object: @machine %>