config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations", as: :anvandare
  }

  resource :user, path: :anvandare

  # Scope to change urls to swedish
  scope path_names: { new: "ny", edit: "redigera" } do
    resources :addresses, path: :adresser

    resources :companies, path: :foretag

    resources :customers, path: :kunder do
      get :company, path: :foretag, on: :member
      resources :addresses, path: :adresser, on: :member

      resources :machines, path: :maskiner, on: :member do
        resources :works, path: :arbete, on: :member
      end
      resources :works, path: :maskiner, on: :member

    end
    resources :cities, path: :stader do
      post :search, :sok, on: :collection
    end

    resources :machines, path: :maskiner
    resources :machine_types, path: :typer
    resources :brands, path: :marke
    resources :products, path: :produkter do
      post :search, on: :collection, path: :sok
    end

    resources :roles
    resources :work_types, path: :arbetstyper
  end

  root "statics#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    elsif user.id.present?
      can [:read, :new, :create, :update, :destroy], :all
      can :search, Product
    else
      can [:new, :create], :session
    end

    if user.role.present?
      user.role.permissions.each do |permission|
        if permission.subject_class == "all"
          can permission.action.to_sym, :all
        else
          can permission.action.to_sym, permission.subject_class.constantize
        end
      end
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
  belongs_to :city

  validates :street, presence: true

  def to_s
    %(#{street}, #{city})
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :machine_models
  has_many :machine_types, through: :machine_models
  has_many :products, through: :machine_models
  has_many :parts, through: :machine_models

  validates :title, :short, presence: true
  validates :short, uniqueness: true

  def to_s
    title
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :addresses

  validates :postal_title, :postal_code, presence: true
  validates :postal_code, uniqueness: true

  def to_s
    %(#{postal_code} #{postal_title})
  end
end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :customers

  has_many :machines, through: :customers
  has_many :products, through: :machines
  has_many :addresses
  has_many :works, through: :machines
  has_many :storages, through: :works

  validates :title, presence: true

  def self.new_path(*)
    Rails.application.routes.url_helpers.new_company_path
  end

  def self.index_path
    Rails.application.routes.url_helpers.companies_path
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_paper_trail

  belongs_to :company

  has_many :machines
  has_many :products, through: :machines
  has_many :addresses
  has_many :works, through: :machines
  has_many :storages, through: :works

  validates :firstname, presence: true
  accepts_nested_attributes_for :addresses, allow_destroy: true

  def to_s
    %(#{firstname} #{lastname})
  end
end

app/models/drive.rb
class Drive < ActiveRecord::Base
  belongs_to :work
  belongs_to :address
  belongs_to :user
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_paper_trail

  belongs_to :customer
  belongs_to :product

  has_many :works
  has_many :parts_used, class_name: :Part, foreign_key: :part_id, through: :works
  has_many :parts, through: :product

  validates :customer, :product, presence: true

  def to_s
    %(#{product})
  end
end

app/models/machine_type.rb
class MachineType < ActiveRecord::Base

  has_many :products
  has_many :brands, through: :products

  validates :title, presence: true

  def to_s
    title
  end
end

app/models/part.rb
class Part < ActiveRecord::Base

  has_many :work_parts
  has_many :work_activities, through: :work_parts
  # Messy, create join models?
  has_many :works, through: :work_activities
  has_many :machines, through: :works
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  has_many :permission_roles, dependent: :destroy
  has_many :roles, through: :permission_roles

  validates :subject_class, :action, presence: true
  validates :subject_class, uniqueness: { scope: :action }


  def to_s
    %(#{action}#{subject_class})
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :parts
  belongs_to :machine_type
  belongs_to :brand

  validates :brand_id, :machine_type_id, :product_nbr,
                       presence: true

  attr_accessor :search

  def to_s
    %(#{brand} #{machine_type} #{product_nbr})
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :permissions, through: :permission_roles
  has_many :permission_roles, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/storage.rb
class Storage < ActiveRecord::Base
  belongs_to :storage_spot
  belongs_to :machine
end

app/models/storage_room.rb
class StorageRoom < ActiveRecord::Base
  has_many :storage_shelves
  has_many :storage_spots
end

app/models/storage_spot.rb
class StorageSpot < ActiveRecord::Base
  belongs_to :storage_shelf
  belongs_to :storage_room
  has_many :storages
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  devise :database_authenticatable, :rememberable, :registerable
  attr_accessor :login
  belongs_to :role
  has_many :work_activities
  has_many :works
  has_many :addresses

  #validates :username,
  #          presence: true,
  #          uniqueness: {
  #              case_sensitive: false
  #          }

  def name
    if firstname? && lastname?
      %(#{firstname} #{lastname})
    else
      email
    end
  end

  def admin?
    role.try(:title) == :admin
  end

  #def self.find_for_database_authentication(warden_conditions)
  #  conditions = warden_conditions.dup
  #  if login = conditions.delete(:login)
  #    where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
   # else
   #   where(conditions.to_hash).first
   # end
  #end

end

app/models/work.rb
class Work < ActiveRecord::Base
  has_paper_trail

  belongs_to :machine
  has_many :work_activities
  has_many :work_parts, through: :work_activities
  has_many :users, through: :work_activities
  has_many :drives
  has_one :storage

  validates :machine, presence: true
end

app/models/work_part.rb
class WorkPart < ActiveRecord::Base
  belongs_to :part
  belongs_to :work_activity
end

app/models/work_type.rb
class WorkType < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_permissions_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @product.save
      redirect_to product_path(@product), notice: alert_create(Product)
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: alert_update(Product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: alert_destroy(Product)
  end

  def search
    a = params[:product][:search].split
    # @b = Brand.find_by(title: a[0])
    @b = Brand.where('title LIKE ?', %(%#{a[0]}%)).first
    # @m = MachineType.find_by(title: a[1])
    @m = MachineType.where('title LIKE ?', %(%#{a[1]}%)).first
    @products = Product.where(brand: @b, machine_type: @m)
    @new_product = Product.find_or_create_by(brand: @b, machine_type: @m)
  end

  private

  def product_params
    params.require(:product).permit(:brand_id, :brand, :machine_type_id,
                                    :machine_type, :product_nbr, :order_nbr)
  end
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class='tab-v1'>
      <ul class='nav nav-justified nav-tabs'>
        <li class='active'><a data-toggle='tab' href='#type-select'>Select WorkType</a></li>
        <li><a data-toggle='tab' href='#type-new'>New WorkType</a></li>
      </ul>
      <div class='tab-content'>
        <div id='type-select' class='brand-select tab-pane fade in active'>
          <%= f.association :machine_type, collection: MachineType.all %>
        </div>
        <div id='type-new' class='profile-edit tab-pane fade'>
          <%= f.simple_fields_for :machine_type, MachineType.new do |p| %>
            <%= render 'machine_types/fields', var: p %>
          <% end %>
        </div>
      </div>
    </div>
    <div class='tab-v1'>
      <ul class='nav nav-justified nav-tabs'>
        <li class='active'>
          <%= link_to(t(:select, attribute: Brand.model_name.human), '#brand-select', data: { toggle: 'tab' }) %>
        </li>
        <li>
          <%= link_to(t(:new, attribute: Brand.model_name.human), '#brand-new', data: { toggle: 'tab' }) %>
        </li>
      </ul>
      <div class='tab-content'>
        <div id='brand-select' class='brand-select tab-pane fade in active'>
          <%= f.association :brand, collection: Brand.all.order(:title) %>
        </div>
        <div id='brand-new' class='brand-edit tab-pane fade'>
          <%= f.simple_fields_for :brand, Brand.new do |p| %>
            <%= render 'brands/fields', var: p %>
          <% end %>
        </div>
      </div>
    </div>
    <%= f.input :product_nbr %>
    <%= f.input :order_nbr %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_search.html.erb
<%= simple_form_for(product, url: search_products_path, remote: true) do |f| %>
  <%= f.input :search %>
  <%= f.submit :button, class: "btn btn-primary" %>
<% end %>
<div id="product-search" class="row">

</div>

app/views/products/_tab.html.erb
<% if products.count > 0 %>
  <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
    <% first = true %>
    <% products.each do |product| %>
      <%= render 'tab_product', product: product %>
    <% end %>
  </ul>
<% end %>

app/views/products/_tab_product.html.erb
<li class="list-group-item">
  <%= link_to(product, :root, class: "fa fa-car") %>
</li>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t(:index, attribute: Product.model_name.human(count: 2)) %></h1>

<table>
  <thead>
    <tr>
      <th><%= Product.human_attribute_name(:machine_type) %></th>
      <th><%= Product.human_attribute_name(:brand) %></th>
      <th><%= Product.human_attribute_name(:product_nbr) %></th>
      <th><%= Product.human_attribute_name(:order_nbr) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.machine_type %></td>
        <td><%= product.brand %></td>
        <td><%= product.product_nbr %></td>
        <td><%= product.order_nbr %></td>
        <td><%= link_to t(:show), product %></td>
        <td><%= link_to t(:edit), edit_product_path(product) %></td>
        <td><%= link_to t(:destroy), product, method: :delete,
          data: { confirm: t(:confirm_destroy) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to(t(:new, attribute: Product.model_name.human), new_product_path) %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search.js.erb
$("#product-search").html("<h3>Sökresultat:</h3>");
$("#product-search").append("Brand: <%= j  @b.to_s %> <br>");
$("#product-search").append("Type: <%= j  @m.to_s %> <br>");
$("#product-search").append("<%= j render("tab", products: @products) %>");
$("#product-search").append("Ny: <%=j link_to(t(:new), new_product_path(@new_product.attributes)) %>");

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Machine type:</strong>
  <%= @product.machine_type %>
</p>

<p>
  <strong>Product nbr:</strong>
  <%= @product.product_nbr %>
</p>

<p>
  <strong>Order nbr:</strong>
  <%= @product.order_nbr %>
</p>

<%= link_to t(:edit), edit_product_path(@product) %> |
<%= link_to t(:back, attr: Product.model_name.human(count: 2).downcase), products_path %>